"""
Generate ai-search/vocab.generated.js from site/data/index.json.

The AI search Worker validates the model's output against this vocabulary, and
ships it to Gemini as `responseSchema` enums so an out-of-vocabulary value is
structurally impossible to emit rather than merely filtered out afterwards.

The vocabulary is therefore a security boundary: it must come from the data we
published, never from the client. It is baked into the Worker at deploy time
(not fetched at runtime) so the AI doesn't depend on GitHub Pages being up.

Run after every data refresh, then redeploy the Worker:

    python tools/gen_vocab.py
    cd ai-search && npx wrangler deploy

Stale vocab fails safe: values the model returns that aren't in it get dropped,
which makes results narrower, never wrong.
"""
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_JSON = REPO_ROOT / "site" / "data" / "index.json"
OUT_JS = REPO_ROOT / "ai-search" / "vocab.generated.js"

# index.json facet name -> the filter key used by currentFilters() in site/js/app.js
# and by AwardSearch.run() in site/js/search.js. Keeping the names identical all
# the way from Gemini's JSON to the browser means there is no translation layer
# anywhere that could drift.
FACET_TO_FILTER_KEY = {
    "career": "career",
    "levels": "level",
    "award_types": "awardType",
    "terms": "term",
    "affiliations": "affiliation",
    "areas_of_study": "areaOfStudy",
}

# Gemini's responseSchema enum lists are the bulk of the prompt's token cost
# (~1050 of ~1500). areas_of_study is 129 values; if it ever grows far beyond
# that, revisit whether the whole list still belongs in the schema.
MAX_ENUM_VALUES = 400


def main():
    if not INDEX_JSON.exists():
        print(f"ERROR: {INDEX_JSON} not found. Run scraper/export_data.py first.", file=sys.stderr)
        return 1

    manifest = json.loads(INDEX_JSON.read_text(encoding="utf-8"))
    facets = manifest.get("facets") or {}

    vocab = {}
    for facet_name, filter_key in FACET_TO_FILTER_KEY.items():
        counts = facets.get(facet_name)
        if not counts:
            print(f"ERROR: facet '{facet_name}' is missing or empty in index.json. "
                  f"Refusing to generate a vocabulary with a hole in it.", file=sys.stderr)
            return 1
        # index.json orders facets by descending count; sort alphabetically so
        # the generated file only changes when the *values* change, not when
        # the counts shuffle. That keeps VOCAB_VERSION (and the response cache)
        # stable across refreshes that add no new filter values.
        values = sorted(counts.keys())
        if len(values) > MAX_ENUM_VALUES:
            print(f"ERROR: facet '{facet_name}' has {len(values)} values, over the "
                  f"{MAX_ENUM_VALUES} cap. Enum lists this large make every request "
                  f"expensive; revisit the schema design.", file=sys.stderr)
            return 1
        vocab[filter_key] = values

    # Version the vocabulary itself, not the dataset: this is a cache-key
    # component, and a data refresh that adds no new filter values should not
    # throw away a warm cache.
    canonical = json.dumps(vocab, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    version = hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]

    lines = [
        "// GENERATED BY tools/gen_vocab.py — DO NOT EDIT BY HAND.",
        "// Source: site/data/index.json (facets). Regenerate after every data",
        "// refresh, then redeploy the Worker: cd ai-search && npx wrangler deploy",
        f"// Generated from data last updated: {manifest.get('last_updated', 'unknown')}",
        "",
        f"export const VOCAB_VERSION = {json.dumps(version)};",
        "",
        "export const VOCAB = {",
    ]
    for filter_key, values in vocab.items():
        lines.append(f"  {filter_key}: [")
        for value in values:
            lines.append(f"    {json.dumps(value, ensure_ascii=False)},")
        lines.append("  ],")
    lines.append("};")
    lines.append("")

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    OUT_JS.write_text("\n".join(lines), encoding="utf-8")

    total = sum(len(v) for v in vocab.values())
    print(f"Wrote {OUT_JS.relative_to(REPO_ROOT)} — {total} values across "
          f"{len(vocab)} filters, VOCAB_VERSION={version}")
    for filter_key, values in vocab.items():
        print(f"  {filter_key}: {len(values)}")
    print("\nReminder: the deployed Worker still has the OLD vocabulary until you run "
          "`cd ai-search && npx wrangler deploy`.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
